vertical_tracker:

  takeoff_speed: 1.0
  takeoff_acceleration: 0.5

  landing_speed: 0.5
  landing_acceleration: 0.3

  # beware, this is for emergency landing only
  elanding_speed: 0.7
  elanding_acceleration: 1.0
