vertical_tracker:

  takeoff_speed: 0.5
  takeoff_acceleration: 1.0

  landing_speed: 0.5
  landing_acceleration: 0.3

  # beware, this is for emergency landing only
  elanding_speed: 1.1
  elanding_acceleration: 1.0
